#cloud-config
users:
  - name: ops
    groups: users, admin, sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCvst/FJr+7BJX98grW3DyXqwwJfb5p5ZyVYdlV0vuGdG4nPg2fos0zT+nx14r1k4Xv+zAVYSME4Zl30hl1UFeKf+bfFidi1/RkyYuy6/FsOnJYkf4LjUOC8c0in5SQrMBS//AyuRQOQWIBt7yjLfHMafSdNUbNIZq34/AmpQwMETWbjeSi9QBxhyRL0PVl22ltWyh31wtXiIaAivllJtoxQuWBjoTwqPaBX8qA73zXNvLypvEKjvBFi7hRW5BHOYyOAztFrk7cYTv+9hqJi0LhUe2YVeihHtZUzzlHgxxrsYjXI217gpJHlijkClv7va0BocWrC5P+hHVKUuqvvn3ZDks3YJKFsy8+Uu1a0f6UVELeVUHvh0l8aRQmP9/rIiWzGcgIOLRKhR0nzdWBK/xydhNNYAMsHz4U+mfFQfLqrC28PCkEjbZlmsTJDX9vYDW36wbON5PsftrTzWKBROEkAlKElgqQ2TB8xFJvWHbgUht4rtwssQjb9dRVpTg/k7E= ops@wallace
bootcmd:
    - printf "[Resolve]\nDNS=8.8.8.8" > /etc/systemd/resolved.conf
    - mkdir -p /operations
    - sudo wget -O /operations/VpsSetup.sh https://raw.githubusercontent.com/Nieuwhof/start/main/VpnSetup.sh
    - chmod +x ./operations/VpsSetup.sh
    - [systemctl, restart, systemd-resolved]

